/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.FlightFinder340.Views;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import main.java.controllers.ControllerBox;
import main.java.models.Trips.Trip;

/**
 *
 * @author Callidus
 */
public class FlightBoxJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightBoxJPanel
     */
    public FlightBoxJPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel130 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(null));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel130.setText("Out Going Take off time ");
        add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 60, -1, -1));

        jLabel119.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel119.setText("Origin");
        add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 38, 160, -1));

        jLabel120.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel120.setText("originDepartureTime");
        add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, -1));

        jLabel121.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel121.setText("originFlightCarrier");
        add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, -1, -1));

        jLabel122.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel122.setText("destination");
        add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 38, 210, -1));

        jLabel123.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel123.setText("inboundDepartureTime");
        add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 85, -1, -1));

        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel124.setText("inboundFlightCarrier");
        add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 105, -1, -1));

        jLabel125.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel125.setText("Price");
        add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 90, 30));

        jLabel126.setText("index");
        add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel127.setText("From:");
        add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 13, -1, -1));

        jLabel128.setText(" To");
        add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 13, -1, -1));

        jLabel129.setText("Out Going Take off time ");
        add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 70, -1));

        jButton1.setText("Add To Trip");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
       
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ControllerBox.getBox().getTripEditCont().setSelectedTrip( jComboBox1.getSelectedIndex());
        
        int index = Integer.parseInt( jLabel126.getText()) -1;
        
        ControllerBox.getBox().getTripEditCont().addQuoteAtIndexToSelectedTrip(index);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);        
        JOptionPane.showMessageDialog( frame, 
                "Flight from "+ jLabel119.getText() +  " to " + jLabel122.getText() + System.lineSeparator()
                + " was added to trip named " + jComboBox1.getItemAt(jComboBox1.getSelectedIndex())
                );

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    // End of variables declaration//GEN-END:variables
}
