/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.FlightFinder340.Views;

import flightfinder3.main.java.FlightFinder340.Views.StandardSearchCollector;
import flightfinder3.main.java.FlightFinder340.Views.StandardSearchView;

/**
 *
 * @author Callidus
 */
public class TripViewerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StandardSearchJPanel
     */
    public TripViewerJPanel() {
        initComponents();
        
        inilize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jpanel10 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jpanel9 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jpanel11 = new javax.swing.JPanel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jpanel12 = new javax.swing.JPanel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(559, 834));
        jPanel3.setEnabled(false);
        jPanel3.setOpaque(false);

        jpanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel131.setText("Origin");
        jLabel131.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel10.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 38, 90, -1));

        jLabel132.setText("originDepartureTime");
        jLabel132.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel10.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, -1));

        jLabel133.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel133.setText("originFlightCarrier");
        jpanel10.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, -1, -1));

        jLabel134.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel134.setText("destination");
        jLabel134.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel10.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 38, 210, -1));

        jLabel135.setText("inboundDepartureTime");
        jLabel135.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel10.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 85, -1, -1));

        jLabel136.setText("inboundFlightCarrier");
        jLabel136.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel10.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 105, -1, -1));

        jLabel137.setText("price");
        jLabel137.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jpanel10.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel138.setText("index");
        jpanel10.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel139.setText("From:");
        jpanel10.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 13, -1, -1));

        jLabel140.setText(" To");
        jpanel10.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 13, -1, -1));

        jLabel141.setText("Out Going Take off time ");
        jpanel10.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        jLabel142.setText("Out Going Take off time ");
        jpanel10.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 60, -1, -1));

        jpanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel119.setText("Origin");
        jLabel119.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel9.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 38, 90, -1));

        jLabel120.setText("originDepartureTime");
        jLabel120.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel9.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, -1));

        jLabel121.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel121.setText("originFlightCarrier");
        jpanel9.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, -1, -1));

        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel122.setText("destination");
        jLabel122.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel9.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 38, 210, -1));

        jLabel123.setText("inboundDepartureTime");
        jLabel123.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel9.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 85, -1, -1));

        jLabel124.setText("inboundFlightCarrier");
        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel9.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 105, -1, -1));

        jLabel125.setText("price");
        jLabel125.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jpanel9.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel126.setText("index");
        jpanel9.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel127.setText("From:");
        jpanel9.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 13, -1, -1));

        jLabel128.setText(" To");
        jpanel9.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 13, -1, -1));

        jLabel129.setText("Out Going Take off time ");
        jpanel9.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        jLabel130.setText("Out Going Take off time ");
        jpanel9.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 60, -1, -1));

        jpanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel143.setText("Origin");
        jLabel143.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel11.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 38, 90, -1));

        jLabel144.setText("originDepartureTime");
        jLabel144.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel11.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, -1));

        jLabel145.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel145.setText("originFlightCarrier");
        jpanel11.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, -1, -1));

        jLabel146.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel146.setText("destination");
        jLabel146.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel11.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 38, 210, -1));

        jLabel147.setText("inboundDepartureTime");
        jLabel147.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel11.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 85, -1, -1));

        jLabel148.setText("inboundFlightCarrier");
        jLabel148.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel11.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 105, -1, -1));

        jLabel149.setText("price");
        jLabel149.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jpanel11.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel150.setText("index");
        jpanel11.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel151.setText("From:");
        jpanel11.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 13, -1, -1));

        jLabel152.setText(" To");
        jpanel11.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 13, -1, -1));

        jLabel153.setText("Out Going Take off time ");
        jpanel11.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        jLabel154.setText("Out Going Take off time ");
        jpanel11.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 60, -1, -1));

        jpanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel155.setText("Origin");
        jLabel155.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel12.add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 38, 90, -1));

        jLabel156.setText("originDepartureTime");
        jLabel156.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel12.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, -1));

        jLabel157.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel157.setText("originFlightCarrier");
        jpanel12.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, -1, -1));

        jLabel158.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel158.setText("destination");
        jLabel158.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel12.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 38, 210, -1));

        jLabel159.setText("inboundDepartureTime");
        jLabel159.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel12.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 85, -1, -1));

        jLabel160.setText("inboundFlightCarrier");
        jLabel160.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpanel12.add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 105, -1, -1));

        jLabel161.setText("price");
        jLabel161.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jpanel12.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel162.setText("index");
        jpanel12.add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel163.setText("From:");
        jpanel12.add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 13, -1, -1));

        jLabel164.setText(" To");
        jpanel12.add(jLabel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 13, -1, -1));

        jLabel165.setText("Out Going Take off time ");
        jpanel12.add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        jLabel166.setText("Out Going Take off time ");
        jpanel12.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 60, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addComponent(jpanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addComponent(jpanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addComponent(jpanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jpanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );

        jLabel50.setText("Trip Viewer");
        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Select Trip");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel50))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel50)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.view.setAllFlightBoxsNext();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.view.setAllFlightBoxsBack();
    }//GEN-LAST:event_jButton1ActionPerformed

     public  void inilize()
    {
       // This helper method is used because the componets passed below can not be referenced from a static context.
       
       
    }   
    
   
    private StandardSearchView view;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel jpanel10;
    private javax.swing.JPanel jpanel11;
    private javax.swing.JPanel jpanel12;
    private javax.swing.JPanel jpanel9;
    // End of variables declaration//GEN-END:variables
}
